### ISSUE TITLE
window class occasionally missing

### ISSUE THREAD

**Issue by astronouth7303** [acrisci/i3ipc-python#10]
```
Traceback (most recent call last):
  File "./disable-standby-fs.py", line 65, in <module>
    i3.main()
  File "/home/astronouth7303/.local/lib/python3.4/site-packages/i3ipc.py", line 311, in main
    event = WindowEvent(data, self)
  File "/home/astronouth7303/.local/lib/python3.4/site-packages/i3ipc.py", line 70, in __init__
    self.container = Con(data['container'], None, conn)
  File "/home/astronouth7303/.local/lib/python3.4/site-packages/i3ipc.py", line 372, in __init__
    self.window_class = data['window_properties']['class']
KeyError: 'class'
```

(Sorry, I don't have more info.)

**Comment by acrisci** [comment]
Fixed in 869f53d.

I'll do a release so you'll have it in the pypi distribution.

**Comment by S0lll0s** [comment]
Hey, you still haven't pushed a release, could you please do so some time soon?

**Comment by acrisci** [comment]
Yeah, sorry. I'll do it today or tomorrow

**Comment by arnarg** [comment]
Any news on this?
