### ISSUE TITLE
typelib not found

### ISSUE THREAD

**Issue by joinmod** [acrisci/i3ipc-python#107]
Hi i installed i3ipc from pip, but he cant found it (ubuntu 18.04 py3)

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 888, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name i3ipc, introspection typelib not found

**Comment by joinmod** [comment]
nevermind i realised what i did wrong
