### ISSUE TITLE
Error with one of the examples: 'Con' object has no attribute 'get_property'

### ISSUE THREAD

**Issue by teto** [acrisci/i3ipc-python#12]
I get this error:
```
$ ./examples/i3-container-commander.py                                                           
Traceback (most recent call last):
  File "./examples/i3-container-commander.py", line 80, in <module>
    g = find_group(c)
  File "./examples/i3-container-commander.py", line 55, in find_group
    return str(container.get_property(args.group_by)) if args.group_by != 'none' else ''
AttributeError: 'Con' object has no attribute 'get_property'
```
but this may be because I use i3-next
```
$ i3 --version                                                                                     
i3 version 4.10.2-145-g37bee99 (2015-04-26, branch "next") © 2009 Michael Stapelberg and contributors
```
Feel free to close it if that's the case

**Comment by acrisci** [comment]
That's a bug in the script. It's using the old api and I didn't update it after the change.
