### ISSUE TITLE
Undeclared Dependency: pubsub

### ISSUE THREAD

**Issue by astronouth7303** [acrisci/i3ipc-python#5]
```
$ sudo pip3 install i3ipc
$ python
>>> import i3ipc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/i3ipc.py", line 6, in <module>
    from pubsub import pub
ImportError: No module named 'pubsub'
```

I can only assume it's referring to the [PyPI package](https://pypi.python.org/pypi/pubsub/0.1.1).

**Comment by astronouth7303** [comment]
For reference, the output of `pip3`:

```
Downloading/unpacking i3ipc
  Downloading i3ipc-1.0.1.tar.gz
  Running setup.py (path:/tmp/pip-build-rq_v7anr/i3ipc/setup.py) egg_info for package i3ipc
    
Downloading/unpacking python3-xlib (from i3ipc)
  Downloading python3-xlib-0.15.tar.gz (132kB): 132kB downloaded
  Running setup.py (path:/tmp/pip-build-rq_v7anr/python3-xlib/setup.py) egg_info for package python3-xlib
    
Installing collected packages: i3ipc, python3-xlib
  Running setup.py install for i3ipc
    
  Running setup.py install for python3-xlib
    
Successfully installed i3ipc python3-xlib
Cleaning up...
```

**Comment by astronouth7303** [comment]
Also, notably, the pubsub repo is now private, so I can't file a bug with them.

**Comment by acrisci** [comment]
pubsub is imported and not used. That is easy to fix :+1:.
