### ISSUE TITLE
focus-last.py does not survive a restart

### ISSUE THREAD

**Issue by bhepple** [acrisci/i3ipc-python#64]
... so it's not really suitable for .xsessionrc as it claims eg. run focus-last.py, do a i3 restart and then a focus-last.py --switch:

`~/ $ ./focus-last.py 

### do an i3 restart, then a focus-last.py --switch:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./focus-last.py", line 68, in launch_server
    callback(key.fileobj)
  File "./focus-last.py", line 51, in read
    tree = self.i3.get_tree()
  File "/usr/lib/python3.6/site-packages/i3ipc.py", line 518, in get_tree
    data = self.message(MessageType.GET_TREE, '')
  File "/usr/lib/python3.6/site-packages/i3ipc.py", line 404, in message
    return self._ipc_send(self.cmd_socket, message_type, payload)
  File "/usr/lib/python3.6/site-packages/i3ipc.py", line 399, in _ipc_send
    sock.sendall(self._pack(message_type, payload))
BrokenPipeError: [Errno 32] Broken pipe
`

**Comment by amazing-horst** [comment]
Thanks for this solution. 
I had to change the escaped quotes in the awk command to make it work:
`exec_always bash -c "ps -ef | awk '/python.*\/focus-last.py/ { system("kill " $2) }'; /foo/bar/baz/focus-last.py`

**Comment by acrisci** [comment]
We can add the recent `auto_reconnect` flag to the connection to fix this.

**Comment by yutakatay** [comment]
It was not disconnected. Thank you :wink:
